/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 A50Product.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/A50Product.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3D_MODEL'].geometry} material={materials['Material.001']} position={[-43.852, 0.036, -101.673]} rotation={[1.565, -0.141, 0.772]} scale={[0.998, 1.001, 0.758]} />
    </group>
  )
}

useGLTF.preload('/A50Product.gltf')
