import {
  icon1,
  icon2,
  icon3,
  icon4,
  icon5,
  icon6,
  icon7,
  icon8,
  icon9,
  icon10,
  icon11,
  icon12,
  icon13,
  icon14,
  icon15,
  icon16,
  icon17,
} from "./icons";

export const iconsFeature = {
  "Heavy duty Railing Systems": icon1,
  "Minimal Railing System": icon2,
  "Fire Rated Gaskets": icon3,
  "Hole Adjustment Feature": icon4,
  "Height Adjustment Option": icon5,
  "3 Part Design": icon6,
  "Ultra Strong and Modern Aesthetics": icon7,
  "High Grade Anti Corrosion": icon8,
  "Better Grip": icon9,
  "Sleek Appearance": icon10,
  "Available in Various Finish": icon11,
  "Inbuild adhesive": icon12,
  "Glass edge profile": icon13,
  "Featured Lighting": icon14,
  "Easy to install Led": icon15,
  "Lighting below eye level": icon16,
  "Led Provision on side": icon17,
};
