/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 A50Product.gltf 
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

interface GLTFResult extends GLTF {
  nodes: {
    Cube: Mesh;
    "3D_MODEL": Mesh;
  };
  materials: {
    Material: MeshStandardMaterial;
  };
}

export default function A50Product(props: GroupProps) {
  const { nodes } = useGLTF("/A50Product.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["3D_MODEL"].geometry}
        material={nodes["3D_MODEL"].material}
        position={[-43.852, -60.036, -101.673]}
        rotation={[1.565, -0.141, 0.772]}
        scale={[0.998, 1.001, 0.758]}
      />
    </group>
  );
}

useGLTF.preload("/A50Product.gltf");
