/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 BlenderProduct.gltf 
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { Mesh, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";

interface GLTFResult extends GLTF {
  nodes: {
    Cube: Mesh;
    "3D_MODEL": Mesh;
  };
  materials: {
    Material: MeshStandardMaterial;
  };
}

export default function BlenderProduct(props: GroupProps) {
  const { nodes } = useGLTF("/BlenderProduct.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["3D_MODEL"].geometry}
        material={nodes["3D_MODEL"].material}
        position={[3.739, 3.218, -68.262]}
        rotation={[1.532, 0.05, 0.601]}
      />
    </group>
  );
}

useGLTF.preload("/BlenderProduct.gltf");
